config:
  envoyGateway:
    gateway:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
    provider:
      type: Kubernetes
    logging:
      level:
        default: info
deployment:
  replicas: 1
  envoyGateway:
    resources:
      requests: { cpu: 50m, memory: 128Mi }
      limits: { memory: 512Mi }
