tempo:
  reportingEnabled: false
  retention: 72h
  resources:
    requests: { cpu: 50m, memory: 256Mi }
    limits: { memory: 1Gi }
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"
  metricsGenerator:
    enabled: true
    remoteWriteUrl: http://kube-prometheus-stack-prometheus.monitoring.svc:9090/api/v1/write
  overrides:
    defaults:
      metrics_generator:
        processors: [service-graphs, span-metrics]
  securityContext:
    allowPrivilegeEscalation: false
    capabilities: { drop: [ALL] }

securityContext:
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  runAsNonRoot: true
  seccompProfile: { type: RuntimeDefault }

persistence:
  enabled: true
  storageClassName: local-path
  size: 5Gi

serviceMonitor:
  enabled: true
