version: v1

replicas: 2

image:
  repository: nginxinc/nginx-unprivileged
  tag: 1.31.6-alpine-otel
  digest: sha256:3468957f1d95cf24ef94e9da7a3c2c9412ea076d704a16e2ef289aa1349413e6

exporter:
  image:
    repository: nginx/nginx-prometheus-exporter
    tag: 1.5.3
    digest: sha256:85666e7fde7e253f1c6d978f9a961245df4c9cdb7677e1866d9bb28e8f9ee41d

resources:
  requests: { cpu: 10m, memory: 32Mi }
  limits: { cpu: 500m, memory: 128Mi }

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

networkPolicy:
  enabled: true
  gatewayNamespace: envoy-gateway-system
  monitoringNamespace: monitoring

tracing:
  enabled: true
  endpoint: opentelemetry-collector.tracing.svc:4317
  collectorNamespace: tracing
