extends: default
ignore: |
  .bin/
  .venv/
  .helm/
  .ansible/
  .state/
  charts/*/templates/
  helmfile/**/*.gotmpl
rules:
  line-length: { max: 160 }
  document-start: disable
  truthy: { check-keys: false }
  comments: { min-spaces-from-content: 1 }
  comments-indentation: false
  braces: { max-spaces-inside: 1 }
  brackets: { max-spaces-inside: 1 }
  indentation: { indent-sequences: consistent }
  octal-values: { forbid-implicit-octal: true, forbid-explicit-octal: true }
