containerd_release_url: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}"
containerd_archive_url: "{{ containerd_release_url }}/containerd-{{ containerd_version }}-linux-{{ node_arch }}.tar.gz"
containerd_runc_base_url: "https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}"
