kubernetes_version: "1.36.5"
kubernetes_minor: "{{ kubernetes_version | regex_replace('^(\\d+\\.\\d+).*$', '\\1') }}"
kubernetes_deb_revision: "1.1"
containerd_version: "2.4.1"
runc_version: "1.5.2"

proxy_https: "{{ lookup('ansible.builtin.env', 'HTTPS_PROXY') }}"
proxy_http: "{{ lookup('ansible.builtin.env', 'HTTP_PROXY') | default(proxy_https, true) }}"
proxy_no: "{{ lookup('ansible.builtin.env', 'NO_PROXY') }},{{ node_ip }}"
proxy_env: >-
  {{ {'http_proxy': proxy_http, 'https_proxy': proxy_https, 'no_proxy': proxy_no,
      'HTTP_PROXY': proxy_http, 'HTTPS_PROXY': proxy_https, 'NO_PROXY': proxy_no}
     if proxy_https | length > 0 else {} }}
registry_mirrors_env: "{{ lookup('ansible.builtin.env', 'REGISTRY_MIRRORS') }}"

containerd_registry_mirrors:
  docker.io:
    server: https://registry-1.docker.io
    mirrors:
      - https://mirror.gcr.io

cluster_name: mts-hack
pod_subnet: 10.244.0.0/16
service_subnet: 10.96.0.0/12

node_ip: "{{ ansible_facts['default_ipv4']['address'] }}"
control_plane_ip: "{{ hostvars[groups['control_plane'][0]]['ansible_facts']['default_ipv4']['address'] }}"

kubeconfig_local_path: "{{ playbook_dir }}/../.state/kubeconfig"

arch_map: { x86_64: amd64, aarch64: arm64 }
node_arch: "{{ arch_map[ansible_facts['architecture']] }}"
