- name: Домашний каталог {{ kube_user }}
  ansible.builtin.getent:
    database: passwd
    key: "{{ kube_user }}"

- name: "~/.kube для {{ kube_user }}"
  ansible.builtin.file:
    path: "{{ ansible_facts['getent_passwd'][kube_user][4] }}/.kube"
    state: directory
    owner: "{{ kube_user }}"
    mode: "0700"

- name: "~/.kube/config для {{ kube_user }}"
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_facts['getent_passwd'][kube_user][4] }}/.kube/config"
    remote_src: true
    owner: "{{ kube_user }}"
    mode: "0600"
