source "https://rubygems.org"

gem "fluentd", "1.19.3"

gem "fluent-plugin-kubernetes_metadata_filter", "3.8.0"
gem "fluent-plugin-grafana-loki", "1.3.0"
gem "fluent-plugin-prometheus", "2.3.0"
gem "fluent-plugin-parser-cri", "0.1.1"
gem "fluent-plugin-concat", "2.6.2"
